[package]
name = "rust-mnist"
version = "0.1.0"
authors = ["BusyBoredom <cwilkin@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "~0.4"
rand = "~0.3"
